# Generated by Django 4.0.4 on 2022-04-21 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBmiInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('Underweight', 'UNDERWEIGHT'), ('Normal', 'NORMAL'), ('Overweight', 'OVERWEIGHT'), ('Obese', 'OBESE')], max_length=15)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
                'default_permissions': {},
            },
        ),
    ]
